const fs = require('fs');

function replaceInFile(path) {
  let code = fs.readFileSync(path, 'utf8');
  code = code.replace(/Anthropic Claude API/g, 'ErMate AI API');
  code = code.replace(/Claude API status/g, 'ErMate AI status');
  code = code.replace(/No differentials generated by Claude Sonnet engine\./g, 'No differentials generated by ErMate AI engine.');
  code = code.replace(/Claude Sonnet clinical decision engine/g, 'ErMate clinical decision engine');
  code = code.replace(/GEMINI_API_KEY is missing/g, 'ErMate API key is missing');
  fs.writeFileSync(path, code);
}

['server/handover.ts', 'server/aiDiagnosis.ts', 'server/extraction.ts', 'server/routes/extraction.routes.ts'].forEach(replaceInFile);
